export const defaultTheme = {
  colorBlackForText: '#333333', 
  colorWhite: '#ffffff',
  colorGray: "#f6f6f6",
  colorForSectionHero: '#D8ECFE', 
  colorForGreenCard: '#E1EDCE',
  colorForRedCard: '#F8DDD7', 
  colorForGreenLabel: '#88AA4D', 
  colorForRedLabel: '#F75531', 
  colorForBtnAndCheckbox: '#FC9B27', 
  colorForBtnHover: '#FC7427',
  pagePadding: '90px', 
  fontFamily: '"Inter", "Arial", sans-serif',
  fontSizeDefault: '18px',
  footerHeight: '80px', 
  pageWidth: '1280px',
}